### ISSUE TITLE
jazzy fails to generate documentation — invalid SWIFT_VERSION

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#1622]
jazzy fails when using the Xcode 10.0 beta 6 (10L232m) toolchain to build the SDK. The issue doesn’t reproduce after selecting Xcode 9.4.1. The stack trace below complains of unsupported arguments, which leads me to think the issue is that we’re specifying Swift 4.0 rather than 4.1 in the podspecs. (The documentation generation script depends on MapboxNavigation-Documentation.podspec.)

https://github.com/mapbox/mapbox-navigation-ios/blob/0ef9ef80a0664fa30d214e031b82bf975f2ceca9/.swift-version#L1
https://github.com/mapbox/mapbox-navigation-ios/blob/0ef9ef80a0664fa30d214e031b82bf975f2ceca9/MapboxNavigation-Documentation.podspec#L53-L57

```
Running xcodebuild
Could not parse compiler arguments from `xcodebuild` output.
Please confirm that `xcodebuild` is building a Swift module.
Saved `xcodebuild` log file: /var/folders/cl/8cgpg37n5cl78pjkbpgml94w0000gn/T/xcodebuild-FBC3D1A4-6317-4132-A379-9F6C1CDF34DD.log
Failed to generate documentation
Traceback (most recent call last):
	12: from /usr/local/bin/jazzy:23:in `<main>'
	11: from /usr/local/bin/jazzy:23:in `load'
	10: from /usr/local/lib/ruby/gems/2.5.0/gems/jazzy-0.9.3/bin/jazzy:15:in `<top (required)>'
	 9: from /usr/local/lib/ruby/gems/2.5.0/gems/jazzy-0.9.3/lib/jazzy/doc_builder.rb:62:in `build'
	 8: from /usr/local/lib/ruby/gems/2.5.0/gems/jazzy-0.9.3/lib/jazzy/podspec_documenter.rb:18:in `sourcekitten_output'
	 7: from /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/config.rb:41:in `with_changes'
	 6: from /usr/local/lib/ruby/gems/2.5.0/gems/jazzy-0.9.3/lib/jazzy/podspec_documenter.rb:23:in `block in sourcekitten_output'
	 5: from /usr/local/lib/ruby/gems/2.5.0/gems/jazzy-0.9.3/lib/jazzy/podspec_documenter.rb:23:in `chdir'
	 4: from /usr/local/lib/ruby/gems/2.5.0/gems/jazzy-0.9.3/lib/jazzy/podspec_documenter.rb:28:in `block (2 levels) in sourcekitten_output'
	 3: from /usr/local/lib/ruby/gems/2.5.0/gems/jazzy-0.9.3/lib/jazzy/podspec_documenter.rb:28:in `map'
	 2: from /usr/local/lib/ruby/gems/2.5.0/gems/jazzy-0.9.3/lib/jazzy/podspec_documenter.rb:32:in `block (3 levels) in sourcekitten_output'
	 1: from /usr/local/lib/ruby/gems/2.5.0/gems/jazzy-0.9.3/lib/jazzy/sourcekitten.rb:230:in `run_sourcekitten'
/usr/local/lib/ruby/gems/2.5.0/gems/jazzy-0.9.3/lib/jazzy/executable.rb:36:in `execute_command': /usr/local/lib/ruby/gems/2.5.0/gems/jazzy-0.9.3/bin/sourcekitten ["doc", "--module-name", "MapboxNavigation", "--", "-target", "MapboxNavigation-Documentation", "SWIFT_VERSION\\=\\\"4.0\\\""] (RuntimeError)

Running xcodebuild

Could not parse compiler arguments from `xcodebuild` output.

Please confirm that `xcodebuild` is building a Swift module.

Saved `xcodebuild` log file: /var/folders/cl/8cgpg37n5cl78pjkbpgml94w0000gn/T/xcodebuild-FBC3D1A4-6317-4132-A379-9F6C1CDF34DD.log

Failed to generate documentation
```

/ref #1134
/cc @friedbunny @frederoni

**Comment by 1ec5** [comment]
Forward-duping to #1682.
